# Generated by Django 5.0.1 on 2025-12-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logs",
            field=models.TextField(blank=True),
        ),
    ]
